version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: orders-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 